//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFermer.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wsr_user_17Entities : DbContext
    {
        public wsr_user_17Entities()
            : base("name=wsr_user_17Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EdinicaIzmerenia> EdinicaIzmerenia { get; set; }
        public virtual DbSet<Fermer> Fermer { get; set; }
        public virtual DbSet<Kachestvo> Kachestvo { get; set; }
        public virtual DbSet<Potrebnost> Potrebnost { get; set; }
        public virtual DbSet<Produkcia> Produkcia { get; set; }
        public virtual DbSet<Proizvodstvo> Proizvodstvo { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<VidProdukcii> VidProdukcii { get; set; }
        public virtual DbSet<ZayavkiFermer> ZayavkiFermer { get; set; }
    }
}
