//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFermer.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkcia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produkcia()
        {
            this.Proizvodstvo = new HashSet<Proizvodstvo>();
        }
    
        public int Id { get; set; }
        public string Nazvanie { get; set; }
        public int Kolichestvo { get; set; }
        public int IdKachetvo { get; set; }
        public decimal OtpysknayaCena { get; set; }
        public int IdVidProdukcii { get; set; }
        public int IdEdinici { get; set; }
    
        public virtual EdinicaIzmerenia EdinicaIzmerenia { get; set; }
        public virtual Kachestvo Kachestvo { get; set; }
        public virtual VidProdukcii VidProdukcii { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proizvodstvo> Proizvodstvo { get; set; }
    }
}
