//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFermer.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZayavkiFermer
    {
        public int Id { get; set; }
        public int IdFermer { get; set; }
        public int IdPotrebnost { get; set; }
        public System.DateTime DataZayavki { get; set; }
        public int IdStatus { get; set; }
        public string Opisanie { get; set; }
    
        public virtual Fermer Fermer { get; set; }
        public virtual Potrebnost Potrebnost { get; set; }
        public virtual Status Status { get; set; }
    }
}
